#!/bin/bash

time_to_wait="10s"
expected_exit_code_with_no_errors="124"

timeout --signal SIGINT "$time_to_wait" R -e "shiny::runApp('~/myapp')"

timeout_exit_code=$?

if [ $timeout_exit_code -ne "$expected_exit_code_with_no_errors" ]
then
    echo "command completed unexpectedly with exit code $timeout_exit_code"
    exit 1
fi

exec "$@"